# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Recreate the archive if needed
        run: tar jcvf python/python-project.tar.bz2 python/python-project

      # Commit changes 
      - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional, but recommended
        # Defaults to "Apply automatic changes"
        commit_message: python project archive automatically updated
        # Optional glob pattern of files which should be added to the commit
        file_pattern: python/*.tar.bz2